language: elixir

env:
  global:
    - ORIENTDB_USER=root
    - ORIENTDB_PASS=root
  matrix:
    - ORIENTDB_VERSION="2.1.12"


elixir:
  - 1.0.5
  - 1.2.2

otp_release:
  - 17.5
  - 18.2.1

before_install:
  - chmod +x ./ci/ci.sh
  - ./ci/ci.sh
  - export PATH="$(pwd)/tmp:$PATH"

script:
  - mix test.all
